'use client';

import React, { useEffect, useRef, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Shield, FileText, ChevronRight, ChevronDown } from 'lucide-react';

type ModalType = 'terms' | 'privacy';

interface LegalModalProps {
  type: ModalType;
  onClose: () => void;
  onRead?: (type: ModalType) => void;
}

const LAST_UPDATED = 'June 1, 2026';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <div className="flex items-center gap-2 mb-3">
        <ChevronRight size={14} className="text-[#e9c176] flex-shrink-0" />
        <h3 className="text-white font-bold text-sm uppercase tracking-widest">{title}</h3>
      </div>
      <div className="pl-5 text-gray-400 text-sm leading-relaxed space-y-2">{children}</div>
    </div>
  );
}

function TermsContent() {
  return (
    <div>
      <p className="text-gray-400 text-sm leading-relaxed mb-8">
        These Terms of Service govern your access to and use of the <strong className="text-white">ilovelawyer</strong> platform
        operated by Law-PH. By creating an account, you confirm that you have read, understood, and agree to be bound
        by these terms.
      </p>

      <Section title="Nature of the Service">
        <p>
          ilovelawyer is an AI-powered legal assistance platform designed to help users understand legal concepts,
          draft documents, and navigate legal processes in the Philippines. The platform is intended as an
          informational and organizational tool only.
        </p>
        <p className="text-[#e9c176]/80 font-medium">
          ilovelawyer does not provide legal advice, does not create an attorney-client relationship, and
          is not a substitute for consultation with a licensed attorney. Always consult a qualified lawyer
          for matters that may affect your legal rights.
        </p>
      </Section>

      <Section title="Eligibility">
        <p>
          You must be at least 18 years of age and capable of entering into a binding agreement to use
          this platform. By registering, you represent and warrant that you meet these requirements.
        </p>
      </Section>

      <Section title="User Accounts">
        <p>
          You are responsible for maintaining the confidentiality of your account credentials and for
          all activity that occurs under your account. You must notify us immediately of any unauthorized
          use of your account.
        </p>
        <p>
          You agree to provide accurate and complete information when creating your account and to keep
          this information up to date.
        </p>
      </Section>

      <Section title="Acceptable Use">
        <p>You agree not to use the platform to:</p>
        <ul className="list-disc list-inside space-y-1 mt-2">
          <li>Upload or transmit unlawful, harmful, or fraudulent content</li>
          <li>Attempt to gain unauthorized access to other user accounts or system infrastructure</li>
          <li>Use the service to harass, threaten, or deceive any person</li>
          <li>Reverse-engineer, scrape, or exploit the platform or its AI systems</li>
          <li>Violate any applicable Philippine or international law</li>
        </ul>
      </Section>

      <Section title="AI-Generated Content Disclaimer">
        <p>
          Responses generated by the AI may contain errors, omissions, or outdated information. The
          platform makes no warranties regarding the accuracy, completeness, or fitness for purpose of
          any AI-generated content. You assume full responsibility for how you act on information
          provided by the platform.
        </p>
      </Section>

      <Section title="Intellectual Property">
        <p>
          All platform software, design, branding, and content (excluding user-submitted content) is
          the exclusive property of Law-PH and is protected under applicable intellectual property
          laws. You may not reproduce, distribute, or create derivative works without written permission.
        </p>
      </Section>

      <Section title="Termination">
        <p>
          We reserve the right to suspend or terminate your account at any time, with or without notice,
          for conduct that violates these Terms or is otherwise harmful to the platform, other users,
          or third parties.
        </p>
      </Section>

      <Section title="Limitation of Liability">
        <p>
          To the maximum extent permitted by law, Law-PH shall not be liable for any indirect,
          incidental, special, or consequential damages arising out of your use of or inability to
          use the platform, even if we have been advised of the possibility of such damages.
        </p>
      </Section>

      <Section title="Changes to These Terms">
        <p>
          We may update these Terms from time to time. Continued use of the platform after changes
          are posted constitutes your acceptance of the revised Terms. We will notify registered
          users of material changes via email or an in-app notice.
        </p>
      </Section>

      <Section title="Governing Law">
        <p>
          These Terms shall be governed by and construed in accordance with the laws of the Republic
          of the Philippines. Any disputes shall be subject to the exclusive jurisdiction of the
          courts of Metro Manila.
        </p>
      </Section>
    </div>
  );
}

function PrivacyContent() {
  return (
    <div>
      <p className="text-gray-400 text-sm leading-relaxed mb-8">
        This Privacy Policy explains how <strong className="text-white">Law-PH</strong> collects, uses, stores,
        and protects your personal information when you use the ilovelawyer platform. We are committed to
        safeguarding your privacy in accordance with the <strong className="text-white">Philippine Data Privacy
        Act of 2012 (Republic Act No. 10173)</strong> and its implementing rules and regulations.
      </p>

      <Section title="Information We Collect">
        <p><strong className="text-white/80">Information you provide directly:</strong></p>
        <ul className="list-disc list-inside space-y-1 mt-1">
          <li>Full name and email address when you register</li>
          <li>Messages, documents, and files you upload or submit through the platform</li>
          <li>Case details, notes, and other content you create within the platform</li>
          <li>Audio recordings you submit for transcription</li>
        </ul>
        <p className="mt-3"><strong className="text-white/80">Information collected automatically:</strong></p>
        <ul className="list-disc list-inside space-y-1 mt-1">
          <li>Browser type, device type, and operating system</li>
          <li>IP address and approximate geographic location</li>
          <li>Pages visited, features used, and timestamps of activity</li>
          <li>Authentication session tokens</li>
        </ul>
      </Section>

      <Section title="How We Use Your Information">
        <p>We process your data solely for the following purposes:</p>
        <ul className="list-disc list-inside space-y-1 mt-2">
          <li>Providing and personalizing the ilovelawyer platform features</li>
          <li>Processing your queries through our AI engine to generate responses</li>
          <li>Storing your cases, documents, and transcriptions in your account</li>
          <li>Sending you account-related notifications and security alerts</li>
          <li>Diagnosing technical issues and improving platform performance</li>
          <li>Complying with legal obligations and responding to lawful requests</li>
        </ul>
        <p className="mt-3 text-[#e9c176]/80 font-medium">
          We do not sell, rent, or trade your personal information to third parties for marketing purposes.
        </p>
      </Section>

      <Section title="Data Storage and Security">
        <p>
          Your data is stored on secure cloud infrastructure (including AWS S3 for uploaded files).
          We implement industry-standard security measures including:
        </p>
        <ul className="list-disc list-inside space-y-1 mt-2">
          <li>Encryption of data in transit (TLS/HTTPS)</li>
          <li>Encryption of sensitive data at rest</li>
          <li>Hashed and salted password storage — we never store your password in plain text</li>
          <li>Role-based access controls limiting who can access your data</li>
          <li>Session expiry and secure token handling</li>
        </ul>
        <p className="mt-3">
          While we take every reasonable precaution, no system is completely immune to security risks.
          We encourage you to use a strong, unique password and to log out when using shared devices.
        </p>
      </Section>

      <Section title="Third-Party Services">
        <p>We use trusted third-party services to operate the platform, including:</p>
        <ul className="list-disc list-inside space-y-1 mt-2">
          <li><strong className="text-white/80">AWS (Amazon Web Services)</strong> — cloud storage and AI transcription</li>
          <li><strong className="text-white/80">Anthropic Claude API</strong> — AI language model powering legal query responses</li>
          <li><strong className="text-white/80">Google OAuth</strong> — optional sign-in via Google account</li>
          <li><strong className="text-white/80">Supabase / PostgreSQL</strong> — secure database infrastructure</li>
        </ul>
        <p className="mt-3">
          These providers are bound by their own privacy policies and data processing agreements.
          We only share the minimum data necessary for each service to function.
        </p>
      </Section>

      <Section title="Your Rights Under the Data Privacy Act">
        <p>As a data subject under RA 10173, you have the right to:</p>
        <ul className="list-disc list-inside space-y-1 mt-2">
          <li><strong className="text-white/80">Access</strong> — request a copy of the personal data we hold about you</li>
          <li><strong className="text-white/80">Correction</strong> — request correction of inaccurate or incomplete data</li>
          <li><strong className="text-white/80">Erasure</strong> — request deletion of your account and associated data</li>
          <li><strong className="text-white/80">Object</strong> — object to processing of your data in certain circumstances</li>
          <li><strong className="text-white/80">Portability</strong> — request a structured, machine-readable copy of your data</li>
          <li><strong className="text-white/80">Complaint</strong> — lodge a complaint with the National Privacy Commission (NPC)</li>
        </ul>
        <p className="mt-3">
          To exercise any of these rights, contact us at{' '}
          <span className="text-[#e9c176]">privacy@ilovelawyer.com</span>. We will respond within 15 business days.
        </p>
      </Section>

      <Section title="Data Retention">
        <p>
          We retain your account data for as long as your account remains active. If you delete your
          account, we will remove your personal data within 30 days, except where retention is required
          by law or for legitimate business purposes (e.g., fraud prevention records).
        </p>
        <p className="mt-2">
          Uploaded audio files and transcriptions are retained until you delete them from your account
          or delete your account entirely.
        </p>
      </Section>

      <Section title="Children's Privacy">
        <p>
          The platform is not directed to persons under 18 years of age. We do not knowingly collect
          personal information from minors. If you believe a minor has provided us with personal data,
          please contact us immediately so we may delete it.
        </p>
      </Section>

      <Section title="Changes to This Policy">
        <p>
          We may revise this Privacy Policy periodically. When we do, we will update the "Last Updated"
          date above and notify registered users via email or an in-app notice. Your continued use of
          the platform after any changes constitutes acceptance of the revised policy.
        </p>
      </Section>
    </div>
  );
}

export function LegalModal({ type, onClose, onRead }: LegalModalProps) {
  const isTerms = type === 'terms';
  const scrollRef = useRef<HTMLDivElement>(null);
  const [hasScrolledToBottom, setHasScrolledToBottom] = useState(false);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
    document.addEventListener('keydown', onKey);
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', onKey);
      document.body.style.overflow = '';
    };
  }, [onClose]);

  const handleScroll = () => {
    const el = scrollRef.current;
    if (!el || hasScrolledToBottom) return;
    const atBottom = el.scrollHeight - el.scrollTop - el.clientHeight < 40;
    if (atBottom) {
      setHasScrolledToBottom(true);
      onRead?.(type);
    }
  };

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-[200] flex items-center justify-center p-4"
        onClick={onClose}
      >
        {/* Backdrop */}
        <div className="absolute inset-0 bg-black/80 backdrop-blur-md" />

        {/* Modal */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 16 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 16 }}
          transition={{ duration: 0.25 }}
          className="relative z-10 w-full max-w-2xl max-h-[85vh] flex flex-col bg-[#0d0d0e] border border-white/10 rounded-3xl shadow-2xl overflow-hidden"
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div className="flex items-center justify-between px-6 py-5 border-b border-white/[0.08] bg-[#111111] flex-shrink-0">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl bg-[#722f37]/20 border border-[#722f37]/30 flex items-center justify-center">
                {isTerms ? <FileText size={16} className="text-[#e9c176]" /> : <Shield size={16} className="text-[#e9c176]" />}
              </div>
              <div>
                <h2 className="text-white font-serif text-lg tracking-tight">
                  {isTerms ? 'Terms of Service' : 'Privacy Policy'}
                </h2>
                <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-gray-500 mt-0.5">
                  Last updated: {LAST_UPDATED}
                </p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="w-8 h-8 flex items-center justify-center rounded-xl text-gray-500 hover:text-white hover:bg-white/[0.08] transition-all"
            >
              <X size={18} />
            </button>
          </div>

          {/* Scrollable body */}
          <div
            ref={scrollRef}
            onScroll={handleScroll}
            className="flex-1 overflow-y-auto px-6 py-6 custom-sidebar-scrollbar"
          >
            {isTerms ? <TermsContent /> : <PrivacyContent />}
          </div>

          {/* Footer */}
          <div className="px-6 py-4 border-t border-white/[0.08] bg-[#111111] flex-shrink-0 flex items-center justify-between gap-4">
            {hasScrolledToBottom ? (
              <p className="text-[10px] text-emerald-400 font-bold uppercase tracking-widest">
                ✓ {isTerms ? 'Terms read' : 'Privacy Policy read'}
              </p>
            ) : (
              <p className="text-[10px] text-gray-500 leading-tight flex items-center gap-1.5">
                <ChevronDown size={12} className="animate-bounce text-[#e9c176]" />
                Scroll to the bottom to acknowledge
              </p>
            )}
            <button
              onClick={onClose}
              disabled={!hasScrolledToBottom}
              className="flex-shrink-0 px-5 py-2.5 text-[11px] font-bold uppercase tracking-widest rounded-xl transition-all active:scale-[0.98] disabled:opacity-40 disabled:cursor-not-allowed bg-[#722f37] hover:bg-[#8b3a44] disabled:hover:bg-[#722f37] text-white"
            >
              I have read this
            </button>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}
